export type StopKind = 'explore' | 'rest' | 'stay';
export interface ItineraryStop {
 id:string; name:string; shortName:string; time:string; duration:string; kind:StopKind;
 category:string; estimatedCost:number; reason:string; story:string;
 lat:number; lng:number; x:number; y:number; travelMinutes:number;
}
export interface JourneyDay { id:number; title:string; subtitle:string; mood:string; stops:ItineraryStop[] }
export const journey:JourneyDay[]=[
 {id:1,title:'Where old Kyoto whispers',subtitle:'Ancient lanes & small discoveries',mood:'A slow day, with room to wander',stops:[
 {id:'kiyomizu',name:'Kiyomizu-dera',shortName:'Kiyomizu-dera',time:'09:00',duration:'90 min',kind:'explore',category:'Culture',estimatedCost:5,reason:'Begin with the temple before the busiest part of the day. An open morning leaves time to linger.',story:'The city falls quiet beneath you. Wooden verandas, a sea of green, and the first deep breath of somewhere new.',lat:34.9949,lng:135.785,x:25,y:30,travelMinutes:0},
 {id:'sannenzaka',name:'Sannenzaka & Ninenzaka',shortName:'Sannenzaka',time:'11:00',duration:'90 min',kind:'explore',category:'Wandering',estimatedCost:18,reason:'A gentle downhill wander connects the morning temple visit to small shops and lunch.',story:'Follow the stone steps, not the clock. A ceramic cup in a shop window. The smell of something warm. Take the turn that calls to you.',lat:34.9966,lng:135.7808,x:41,y:52,travelMinutes:15},
 {id:'matcha',name:'A moment for matcha',shortName:'Matcha pause',time:'13:00',duration:'60 min',kind:'rest',category:'Food & drink',estimatedCost:12,reason:'A deliberate break between walking stretches. The café is an illustrative stop to be resolved when live Places is connected.',story:'A green bowl, a quiet corner, a little sweetness. Let the world keep moving while you sit perfectly still.',lat:35.0001,lng:135.7786,x:61,y:58,travelMinutes:12},
 {id:'gion',name:'An evening in Gion',shortName:'Gion',time:'17:00',duration:'2 hours',kind:'explore',category:'Culture',estimatedCost:32,reason:'Keep the afternoon open, then return to the historic lanes for a slow evening and dinner.',story:'As the light softens, the lanterns begin their work. Walk softly through the lanes. This is a neighborhood, and you are its guest.',lat:35.003,lng:135.775,x:54,y:78,travelMinutes:18},
 {id:'ryokan',name:'Rest at your ryokan',shortName:'Your ryokan',time:'20:00',duration:'Overnight',kind:'stay',category:'Accommodation',estimatedCost:85,reason:'A sample lodging allowance, not a reservation. End nearby and save your energy for tomorrow.',story:'Shoes off. Tea poured. The day settles into memory. Tomorrow can wait.',lat:35.006,lng:135.772,x:32,y:81,travelMinutes:15}
 ]},
 {id:2,title:'Into the green',subtitle:'Bamboo paths & riverside pauses',mood:'A little nature. A lot of breathing room.',stops:[
 {id:'bamboo',name:'Arashiyama bamboo grove',shortName:'Bamboo grove',time:'08:30',duration:'90 min',kind:'explore',category:'Nature',estimatedCost:0,reason:'Start in the grove and keep the day focused on Arashiyama to limit backtracking.',story:'Tall green stems lean toward the sky. Above you, the leaves make their own kind of music.',lat:35.0094,lng:135.6668,x:31,y:23,travelMinutes:0},
 {id:'tenryu',name:'Tenryū-ji gardens',shortName:'Tenryū-ji',time:'10:30',duration:'90 min',kind:'explore',category:'Gardens',estimatedCost:6,reason:'Pair the grove with a nearby garden and leave enough time to sit by the pond.',story:'A garden that asks nothing of you. Watch a reflection shift. Notice how much can happen when you slow down.',lat:35.0157,lng:135.6737,x:25,y:43,travelMinutes:10},
 {id:'riverside',name:'Lunch by the river',shortName:'Riverside lunch',time:'12:30',duration:'75 min',kind:'rest',category:'Food & drink',estimatedCost:24,reason:'Lunch and a seated break before the afternoon river walk. Restaurant selection comes with live search.',story:'Find a seat with a view of the water. Something warm to eat. Nowhere you need to rush.',lat:35.0105,lng:135.6781,x:68,y:46,travelMinutes:15},
 {id:'bridge',name:'Togetsukyō Bridge',shortName:'Togetsukyō',time:'15:00',duration:'60 min',kind:'explore',category:'Nature',estimatedCost:0,reason:'An unhurried walk along the river rounds out a day outdoors.',story:'The river carries the afternoon away. Cross the bridge, look back at the hills, and let the view become a memory.',lat:35.0095,lng:135.6781,x:77,y:66,travelMinutes:8},
 {id:'ryokan2',name:'A quiet night in Kyoto',shortName:'Back to rest',time:'19:00',duration:'Overnight',kind:'stay',category:'Accommodation',estimatedCost:115,reason:'Includes sample dinner and lodging allowances. The return train is illustrative until live directions are connected.',story:'The train windows catch the last light. Back in your room, the green of the day stays with you.',lat:35.006,lng:135.772,x:38,y:81,travelMinutes:45}
 ]},
 {id:3,title:'Follow your curiosity',subtitle:'Vermilion gates & one last taste',mood:'A bright final chapter, at your own pace',stops:[
 {id:'fushimi',name:'Fushimi Inari Taisha',shortName:'Fushimi Inari',time:'08:00',duration:'2 hours',kind:'explore',category:'Culture',estimatedCost:0,reason:'Leave a generous morning for the shrine. Walk as far as feels right; the full mountain route is optional.',story:'One gate, then another. The vermilion path winds into the trees. There is no perfect distance to go. Only your own.',lat:34.9671,lng:135.7727,x:22,y:31,travelMinutes:0},
 {id:'nishiki',name:'A taste of Nishiki Market',shortName:'Nishiki Market',time:'12:00',duration:'90 min',kind:'explore',category:'Food & drink',estimatedCost:30,reason:'A flexible lunch lets you sample small dishes without committing to a fixed menu.',story:'Pick the thing you have never tried. Ask a question. Let lunch become a handful of small adventures.',lat:35.005,lng:135.7649,x:41,y:70,travelMinutes:35},
 {id:'coffee',name:'Coffee & a postcard',shortName:'Postcard pause',time:'14:00',duration:'60 min',kind:'rest',category:'Food & drink',estimatedCost:10,reason:'An intentional pause to write, reflect, or simply do nothing. Café details are sample data.',story:'Dear someone. Or dear future you. Write down the little thing you do not want to forget.',lat:35.007,lng:135.768,x:60,y:59,travelMinutes:10},
 {id:'kamo',name:'Along the Kamo River',shortName:'Kamo River',time:'16:00',duration:'90 min',kind:'explore',category:'Nature',estimatedCost:0,reason:'Finish with an open stretch of the day and a riverside walk before departure.',story:'One last walk beside the water. You arrived with a plan. You leave with a story.',lat:35.012,lng:135.771,x:77,y:47,travelMinutes:12},
 {id:'station',name:'Until next time, Kyoto',shortName:'Kyoto Station',time:'18:30',duration:'Departure',kind:'rest',category:'Transport',estimatedCost:15,reason:'A sample local transfer allowance. Intercity fares and departure schedules are not included.',story:'A window seat. A city slipping into the distance. Some places travel home with you.',lat:34.9858,lng:135.7588,x:48,y:84,travelMinutes:25}
 ]}
];
export const totalEstimate=journey.reduce((a,d)=>a+d.stops.reduce((s,p)=>s+p.estimatedCost,0),0);

