"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Play,Pause,Compass,CalendarDays,Users,Sparkles,ChevronRight,ChevronLeft,Footprints,Coffee,BedDouble,Leaf,Wallet,SlidersHorizontal,RotateCcw,Camera,UtensilsCrossed,TrainFront,Check,ArrowRight,MapPin} from 'lucide-react';
import Landing from '@/components/travel/landing';
import TravelBrief from '@/components/travel/travel-brief';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Slider} from '@/components/ui/slider';
import {Progress} from '@/components/ui/progress';
import StoryMap,{travelPoint} from '@/components/travel/story-map';
import PlannerForm from '@/components/travel/planner-form';
import {createDemoTrip,defaultPreferences,destinations,type TripPreferences} from '@/lib/travel/destinations';
export default function Home(){
 const [home,setHome]=useState(true),[briefOpen,setBriefOpen]=useState(false);
 const [preferences,setPreferences]=useState(defaultPreferences),[draft,setDraft]=useState(defaultPreferences),[planning,setPlanning]=useState(true),[dayIndex,setDayIndex]=useState(0),[selected,setSelected]=useState(0),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[immersive,setImmersive]=useState(false),[budgetOpen,setBudgetOpen]=useState(false),[budgetDraft,setBudgetDraft]=useState(defaultPreferences.budget),[reducedMotion,setReducedMotion]=useState(false),[details,setDetails]=useState(false),[speed,setSpeed]=useState(1);
 const effective=planning?draft:preferences;
 const destination=destinations.find(d=>d.id===effective.destinationId)!;
 const days=useMemo(()=>createDemoTrip(effective),[effective]);
 const day=days[Math.min(dayIndex,days.length-1)]??days[0];const safeSelected=Number.isFinite(selected)?Math.max(0,Math.min(selected,day.stops.length-1)):0,stop=day.stops[safeSelected]??day.stops[0];const point=travelPoint(day,progress);
 const total=days.reduce((n,d)=>n+d.stops.reduce((s,p)=>s+p.estimatedCost,0),0)*effective.travelers;
 const percent=total/effective.budget*100;const remaining=effective.budget-total;
 const chooseStop=(i:number)=>{setSelected(i);setProgress(i/(day.stops.length-1)*100);setPlaying(false);setDetails(false)};
 const chooseDay=(i:number)=>{setDayIndex(i);setSelected(0);setProgress(0);setPlaying(false);setDetails(false)};
 const changeDraft=(p:TripPreferences)=>{setDraft(p);chooseDay(0)};
 const plan=()=>{setPreferences(draft);chooseDay(0);setPlanning(false)};
 const date=(i:number,options:Intl.DateTimeFormatOptions={month:'short',day:'numeric'})=>{const d=new Date(effective.startDate+'T12:00:00');if(!Number.isFinite(d.getTime()))return 'Choose dates';d.setDate(d.getDate()+i);return d.toLocaleDateString('en-US',options)};
 const play=()=>{if(progress>=100){setProgress(0);setSelected(0)}setPlaying(p=>!p)};
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setReducedMotion(media.matches);const change=()=>setReducedMotion(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 useEffect(()=>{if(!playing)return;let frame:number,last=performance.now();const tick=(now:number)=>{const elapsed=Math.min(now-last,100);last=now;setProgress(p=>Math.min(100,p+elapsed/450*speed));frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing,speed]);
 useEffect(()=>{if(playing){const i=Math.min(day.stops.length-1,Math.floor(progress/100*(day.stops.length-1)));setSelected(i);if(progress>=100)setPlaying(false)}},[progress,playing,day.stops.length]);
 useEffect(()=>{if(!immersive)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setImmersive(false)};document.addEventListener('keydown',close);return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',close)}},[immersive]);
 // Small structured tools let an agent inspect and operate this demo without external requests.
 useEffect(()=>{const context=(navigator as Navigator&{modelContext?:{registerTool:(t:unknown)=>void;unregisterTool:(name:string)=>void}}).modelContext;if(!context)return;const tools=[{name:'get_travel_preview',description:'Read the currently displayed curated travel preview. All prices and routes are sample data.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({destination:destination.label,preferences:effective,day:dayIndex+1,selectedStop:stop.name,estimatedTotal:total,sample:true})}]})},{name:'select_journey_chapter',description:'Select a day in the current travel preview.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:days.length}},required:['day']},execute:async(input:{day:number})=>{if(!Number.isInteger(input.day)||input.day<1||input.day>days.length)throw Error('Invalid chapter');chooseDay(input.day-1);return {content:[{type:'text',text:`Selected day ${input.day}`}]}}}];tools.forEach(t=>context.registerTool(t));return()=>tools.forEach(t=>context.unregisterTool(t.name))},[effective,dayIndex,stop.name,total,days.length,destination.label]);
 const traveling=playing&&point.moving;const nextIndex=Number.isFinite(point.index)?Math.max(0,Math.min(point.index+1,day.stops.length-1)):0;const nextStop=day.stops[nextIndex]??stop;
 const ActivityIcon=traveling?(nextStop.travelMinutes>=35?TrainFront:Footprints):stop.kind==='stay'?BedDouble:stop.category.toLowerCase().includes('food')?(stop.name.toLowerCase().match(/matcha|coffee|café/)?Coffee:UtensilsCrossed):stop.kind==='rest'?Coffee:Camera;
 const activityLabel=traveling?(nextStop.travelMinutes>=35?'Watching the world go by':'Taking the scenic way'):stop.kind==='stay'?'Resting & recharging':ActivityIcon===Coffee?'Sipping. Sitting. Slowing down.':ActivityIcon===UtensilsCrossed?'A taste of somewhere new':'A little more exploring';
 if(home)return <><Landing onPlan={()=>setBriefOpen(true)} onDemo={()=>{setHome(false);setPlanning(false);chooseDay(0);window.scrollTo(0,0)}} reducedMotion={reducedMotion}/><TravelBrief open={briefOpen} onOpenChange={setBriefOpen} onDemo={()=>{setHome(false);setPlanning(false);chooseDay(0);window.scrollTo(0,0)}}/></>;
 return <main className={`app-shell ${planning?'planning-mode':'journey-mode'} ${immersive?'immersive-mode':''}`}>
 <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setHome(true);setPlaying(false);window.scrollTo(0,0)}} aria-label="Roam travel planner home"><Compass/><b>roam<span>.</span></b></a><span className="brand-label">TRAVEL, WITH A LITTLE WONDER</span><nav aria-label="Main navigation"><button className={planning?'nav-active':''} onClick={()=>{setPlanning(true);setDraft(preferences);chooseDay(0)}}>Shape this example</button><button className={!planning?'nav-active':''} onClick={()=>{setPlanning(false);chooseDay(0)}}>Sample itinerary</button></nav><button className="header-budget" onClick={()=>{setBudgetDraft(effective.budget);setBudgetOpen(true)}}><Wallet size={16}/><span>Trip budget</span></button></header>
 <div className="workspace"><aside className="journal">
 {planning?<div className="planner-intro"><div className="eyebrow"><span className="tiny-line"/> SHAPE YOUR SAMPLE JOURNEY</div><h1>Make this journey<br/><em>a little more you.</em></h1><p className="intro">A few little details. A whole world of possibilities. Let’s make a journey that feels like you.</p><PlannerForm value={draft} onChange={changeDraft} onSubmit={plan}/></div>:<>
 <button className="back-to-planner" onClick={()=>{setPlanning(true);setDraft(preferences);setPlaying(false)}}><ArrowLeft size={14}/>Shape your trip</button><div className="eyebrow">YOUR NEXT CHAPTER</div><h1 className="trip-title">{destination.name}<em>, a little deeper.</em></h1><div className="trip-meta"><span><CalendarDays size={14}/>{date(0)} – {date(days.length-1)}</span><span><Users size={14}/>{effective.travelers} travelers</span></div>
 <div className="section-heading"><h3>Your story, day by day</h3><BookOpen size={17}/></div><Tabs value={String(dayIndex)} onValueChange={v=>chooseDay(Number(v))}><TabsList className="day-tabs">{days.map((d,i)=><TabsTrigger key={d.id} value={String(i)}>Day {i+1}<small>{date(i).toUpperCase()}</small></TabsTrigger>)}</TabsList></Tabs>
 <div className="chapter-title"><span>CHAPTER 0{dayIndex+1}</span><h2>{day.title}</h2><p><Leaf size={14}/>{day.mood}</p></div>
 <div className="stop-list">{day.stops.map((s,i)=>{const Icon=s.kind==='rest'?Coffee:s.kind==='stay'?BedDouble:Compass;return <div key={s.id}><button className={'stop '+(i===safeSelected?'selected':'')} onClick={()=>chooseStop(i)} aria-pressed={i===safeSelected}><span className="stop-icon"><Icon size={17}/></span><span><small>{s.time}<span> · {s.kind.toUpperCase()}</span></small><strong>{s.name}</strong><p>{s.duration} · ${s.estimatedCost}/person</p></span><ChevronRight size={15}/></button>{i<day.stops.length-1&&<div className="travel-connector"><Footprints size={11}/><span>{day.stops[i+1].travelMinutes} min {day.stops[i+1].travelMinutes>=35?'transfer':'walk'} · sample</span></div>}</div>})}</div>
 <div className="agent-note"><Sparkles size={18}/><p>Room for the unplanned.<br/><span>A little breathing room is part of the plan.</span></p></div></>}
 <button className={`budget-summary ${remaining<0?'over-budget':''}`} onClick={()=>{setBudgetDraft(effective.budget);setBudgetOpen(true)}}><div><Wallet size={16}/><span>{planning?'Preview estimate':'Your trip budget'}</span><ChevronRight size={15}/></div><strong>${total.toLocaleString()} <span>/ ${effective.budget.toLocaleString()}</span></strong><Progress value={Math.min(100,percent)} aria-label="Estimated trip budget used"/><small>{remaining<0?`$${Math.abs(remaining).toLocaleString()} over your budget`:`$${remaining.toLocaleString()} left for little discoveries`} · {effective.travelers} {effective.travelers===1?'person':'people'}</small></button>
 </aside><section className="experience" aria-label="Travel journey preview"><div className="scene-heading"><div><div className="eyebrow"><span className="live-spark"/><span>{planning?'A LITTLE PREVIEW OF WHAT’S POSSIBLE':'YOUR JOURNEY, BROUGHT TO LIFE'}</span></div><h2>{planning?'Don’t just plan it. Feel it.':day.title}</h2></div><span className="demo-label">Interactive demo</span></div>
 <div className="destination-strip" aria-label="Preview destination">{destinations.map(d=><button key={d.id} className={d.id===destination.id?'active':''} onClick={()=>{if(!planning){setPlanning(true);setDraft({...preferences,destinationId:d.id})}else setDraft({...draft,destinationId:d.id});chooseDay(0)}}><MapPin size={13}/>{d.name}<span>{d.country}</span>{d.id===destination.id&&<Check size={13}/>}</button>)}</div>
 <div className="scene-container" key={destination.id}><StoryMap destination={destination} day={day} selected={safeSelected} progress={progress} playing={playing} onSelect={chooseStop} immersive={immersive} setImmersive={setImmersive} reducedMotion={reducedMotion}/><div className="scene-location"><span>{destination.country.toUpperCase()}</span><h2>{destination.name}<i>.</i></h2><p>{destination.subtitle}</p></div></div>
 <div className={`story-card ${traveling?'in-transit':stop.kind}`}><div className={`activity-visual ${playing?'animating':''} activity-${ActivityIcon===Coffee?'coffee':ActivityIcon===BedDouble?'sleep':traveling?'walk':'explore'}`} aria-hidden="true"><div className="activity-orbit"/><ActivityIcon size={34} strokeWidth={1.4}/><span className="activity-spark one"/><span className="activity-spark two"/><span className="activity-spark three"/>{ActivityIcon===BedDouble&&<i className="sleep-z">z z</i>}</div><div className="story-copy" key={stop.id+(traveling?'travel':'stop')}><span className="activity-label">{traveling?'ON THE WAY':stop.kind==='stay'?'TIME TO REST':stop.kind==='rest'?'A LITTLE PAUSE':'IN THIS MOMENT'}<i/> {traveling?nextStop.travelMinutes+' MIN':stop.time}</span><h3>{activityLabel}</h3><p>{traveling?`Next, ${nextStop.name}. The journey between places is part of the story, too.`:stop.story}</p><button className="reason-button" onClick={()=>setDetails(!details)} aria-expanded={details}><Sparkles size={13}/>{details?'Hide the thinking':'Why this moment?'}<ChevronRight size={13}/></button>{details&&<p className="reason-text">{stop.reason}</p>}</div></div>
 <footer className="playback"><button className="play-button" onClick={play} aria-label={playing?'Pause journey':'Play journey'}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><div className="playback-main"><div className="playback-top"><button className="playback-prompt" onClick={play} aria-label={playing?'Pause journey':'Play journey'}>{progress>=100?'A chapter to remember.':playing?'Your story is unfolding…':progress===0?'Take a little journey.':'Pick up where you left off.'}</button><span>CHAPTER 0{dayIndex+1} / 0{days.length}</span></div><Slider min={0} max={100} step={.1} value={[Number.isFinite(progress)?progress:0]} onValueChange={v=>{const next=v[0];if(typeof next!=='number'||!Number.isFinite(next))return;setProgress(next);setSelected(Math.min(day.stops.length-1,Math.floor(next/100*(day.stops.length-1))));setPlaying(false)}} aria-label="Journey playback position"/><div className="timeline-labels"><span>{day.stops[0].time}</span><span>{day.stops.at(-1)?.time}</span></div></div><div className="playback-actions"><button aria-label="Restart journey" onClick={()=>{setProgress(0);setSelected(0);setPlaying(false)}}><RotateCcw size={16}/></button><button className="speed-button" aria-label={`Playback speed ${speed} times. Change speed`} onClick={()=>setSpeed(s=>s===1?2:1)}>{speed}×</button><button aria-label="Next chapter" disabled={dayIndex===days.length-1} onClick={()=>chooseDay(dayIndex+1)}><ChevronRight size={21}/></button></div></footer>
 <div className="bottom-note"><span><span className="green-dot"/>{reducedMotion?'Reduced motion enabled':'Drag to explore · press play to follow the day'}</span><span>Good journeys leave room for wonder <Sparkles size={13}/></span></div>
 </section></div>
 <Dialog open={budgetOpen} onOpenChange={setBudgetOpen}><DialogContent className="budget-dialog"><DialogHeader><DialogTitle>Your budget, your pace.</DialogTitle><DialogDescription>Sample estimates in USD for {effective.travelers} {effective.travelers===1?'traveler':'travelers'}. Flights, insurance and real-time prices are not included.</DialogDescription></DialogHeader><div className="budget-breakdown">{days.map((d,i)=><div key={d.id}><span>Day {i+1} · {d.title}</span><strong>${d.stops.reduce((s,p)=>s+p.estimatedCost,0)*effective.travelers}</strong></div>)}<div className="budget-total"><span>Estimated total</span><strong>${total}</strong></div></div><form onSubmit={e=>{e.preventDefault();if(budgetDraft<50)return;setPreferences(p=>({...p,budget:budgetDraft}));setDraft(p=>({...p,budget:budgetDraft}));setBudgetOpen(false)}}><label className="field-label" htmlFor="edit-budget">Your total trip budget</label><div className="money-input"><span>$</span><input id="edit-budget" type="number" min="50" max="100000" required value={budgetDraft||''} onChange={e=>setBudgetDraft(Number(e.target.value))}/></div><button className="primary-cta" type="submit">Save budget<Check size={18}/></button></form></DialogContent></Dialog>
 </main>
}

