"use client";
import {ArrowUpRight,ArrowRight,Compass,Play,Pause,MapPin,Footprints,Coffee,BedDouble,Camera,Route,SlidersHorizontal,Wallet,Check,ChevronDown,Sparkles,Leaf} from 'lucide-react';
import {useEffect,useState} from 'react';
const moments=[{label:'Taking it all in',place:'A temple in the treetops',time:'09:00',type:'EXPLORE',icon:Camera,x:29,y:29},{label:'The journey is part of it',place:'A little wandering between stops',time:'11:00',type:'ON THE WAY',icon:Footprints,x:47,y:49},{label:'A little room to breathe',place:'Matcha, and a moment to yourself',time:'13:00',type:'REST',icon:Coffee,x:62,y:59},{label:'Follow the evening light',place:'A new story around every corner',time:'17:00',type:'DISCOVER',icon:Compass,x:52,y:76},{label:'Tomorrow can wait',place:'Rest. Recharge. Dream a little.',time:'20:00',type:'STAY',icon:BedDouble,x:29,y:79}];
export default function Landing({onPlan,onDemo,reducedMotion}:{onPlan:()=>void;onDemo:()=>void;reducedMotion:boolean}){
const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false);const moment=moments[index],Icon=moment.icon;
useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>(i+1)%moments.length),4300);return()=>clearInterval(timer)},[playing]);
return <div className="landing">
<header className="landing-header"><a className="brand" href="#"><Compass/><b>roam<span>.</span></b></a><nav aria-label="Website navigation"><a href="#experience">The experience</a><a href="#how-it-works">How it works</a><button onClick={onDemo}>Explore the demo<ArrowUpRight size={14}/></button></nav><button className="nav-plan" onClick={onPlan}>Start planning<ArrowUpRight size={15}/></button></header>
<section className="landing-hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> YOUR NEXT GREAT STORY STARTS HERE</div><h1>More than a trip.<br/>A story <em>only<br/>you could live.</em></h1><p>The places you’ll discover. The paths between them. The moments you’ll slow down for. Bring it all together in a journey that feels like you.</p><div className="hero-actions"><button className="hero-cta" onClick={onPlan}>Let’s plan your next chapter<ArrowUpRight size={19}/></button><button className="hero-secondary" onClick={onDemo}><span><Play size={12} fill="currentColor"/></span>See it in motion</button></div><div className="hero-smallprint"><span><Compass size={14}/>Anywhere you imagine</span><span><Leaf size={14}/>Always at your pace</span></div><div className="hero-footnote">An early look at a more thoughtful way to travel.</div></div>
<div className={`hero-world ${playing?'is-playing':''}`}><div className="hero-world-canvas"><img src="/kyoto-diorama.webp" alt="An example travel story visualized as a cinematic miniature landscape of Kyoto"/><div className="hero-world-shade"/><svg className="hero-route" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true"><path d="M290 290 C450 290 360 490 470 490 S610 530 620 590 S600 720 520 760 S360 750 290 790"/></svg>{moments.map((m,i)=>{const Pin=m.icon;return <button key={m.type} className={`hero-scene-pin ${index===i?'active':''}`} style={{left:m.x+'%',top:m.y+'%'}} onClick={()=>{setIndex(i);setPlaying(false)}} aria-label={`Preview activity: ${m.type.toLowerCase()}`} aria-pressed={index===i}><Pin size={16}/></button>})}<div className="hero-example-label"><span>THE STORYBOOK VIEW</span><small>Kyoto, Japan · an example journey</small></div><div className="hero-coordinates"><Compass size={25}/><span>N</span></div><div className="hero-bottom-caption">A world of possibilities.<br/><em>Your own way through.</em></div></div>
<div className="hero-filmstrip"><button onClick={()=>setPlaying(!playing)} aria-label={playing?'Pause sample activities':'Play sample activities'}>{playing?<Pause size={14} fill="currentColor"/>:<Play size={14} fill="currentColor"/>}</button><span>One day. A thousand little moments.</span><div>{moments.map((m,i)=><button key={m.type} className={index===i?'active':''} onClick={()=>{setIndex(i);setPlaying(false)}} aria-label={`Show ${m.type.toLowerCase()} moment`}/>)}</div></div></div></section>
<div className="value-ribbon"><span>A little less planning.<br/><em>A lot more living.</em></span><div><Route/><p>Your route,<br/><strong>brought to life</strong></p></div><div><Coffee/><p>Room for<br/><strong>the little pauses</strong></p></div><div><Wallet/><p>Your budget,<br/><strong>in the picture</strong></p></div><div><SlidersHorizontal/><p>A journey<br/><strong>on your terms</strong></p></div></div>
<section id="experience" className="experience-section"><div className="section-intro"><div className="eyebrow">THE EXPERIENCE</div><h2>See the journey.<br/><em>Not just the itinerary.</em></h2><p>A list tells you where to be. Your travel story shows how the whole day comes together.</p><button className="text-link" onClick={onDemo}>Step inside a sample journey<ArrowUpRight size={17}/></button></div><div className="feature-stories"><article><span className="feature-number">01</span><div><h3>Every step has a place.</h3><p>Explore an illustrated route, select a stop, and move through the day. Zoom out for the big picture. Lean in for the little details.</p><span className="feature-tag"><Route size={12}/> INTERACTIVE STORY MAP</span></div></article><article><span className="feature-number">02</span><div><h3>Make space for being there.</h3><p>Watch your day shift from exploring to travelling, from a coffee break to a good night’s rest. Because downtime belongs in the plan, too.</p><span className="feature-tag"><Coffee size={12}/> ACTIVITIES & REST, IN MOTION</span></div></article><article><span className="feature-number">03</span><div><h3>Keep the trip feeling like you.</h3><p>Set your budget, find your rhythm, and choose what you care about. See sample costs change as you shape your journey.</p><span className="feature-tag"><SlidersHorizontal size={12}/> YOUR PACE. YOUR PRIORITIES.</span></div></article></div></section>
<section id="how-it-works" className="how-section"><div className="eyebrow">FROM A LITTLE IDEA TO A GREAT ADVENTURE</div><h2>Less back and forth.<br/><em>More looking forward.</em></h2><div className="how-steps"><article><span>01 / DREAM IT</span><div className="step-icon"><MapPin size={25}/></div><h3>Start with somewhere.</h3><p>A place you can’t stop thinking about. Your dates, your people, your budget. Every journey starts with you.</p></article><article><span>02 / SHAPE IT</span><div className="step-icon"><SlidersHorizontal size={25}/></div><h3>Find your kind of day.</h3><p>Slow mornings or a little more adventure? Food, nature, culture? Bring your preferences into the picture.</p></article><article><span>03 / FEEL IT</span><div className="step-icon"><Play size={24}/></div><h3>Watch the story unfold.</h3><p>Follow the route. See the activities. Leave room for a pause. Explore what the day could feel like before you go.</p></article></div><p className="preview-note">You’re exploring the UI preview. Live AI planning, verified directions and booking connections are the next chapter.</p></section>
<section className="closing-cta"><div><span className="eyebrow">THERE’S A WHOLE WORLD OUT THERE</span><h2>Where to <em>next?</em></h2><p>You bring the daydream. Let’s give it a little direction.</p></div><button onClick={onPlan}>Start your travel story<ArrowUpRight size={20}/></button></section>
<footer className="landing-footer"><a className="brand" href="#"><Compass/><b>roam<span>.</span></b></a><span>Made for the journey. And the detours.</span><button onClick={onDemo}>Explore the interactive demo<ArrowUpRight size={14}/></button><small>© {new Date().getFullYear()} Roam</small></footer>
</div>}
