"use client";
import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight,MapPin,CalendarDays,Users,Wallet,Compass,Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Itinerary} from '@/lib/types';

type AgentState='idle'|'thinking'|'ready'|'error';
type Props={open:boolean;onOpenChange:(v:boolean)=>void;onDemo:()=>void};

export default function TravelBrief({open,onOpenChange,onDemo}:Props){
 const [place,setPlace]=useState(''),[date,setDate]=useState(''),[travelers,setTravelers]=useState(2),[budget,setBudget]=useState(1000),[interests,setInterests]=useState(''),[ready,setReady]=useState(false),[agentState,setAgentState]=useState<AgentState>('idle'),[itinerary,setItinerary]=useState<Itinerary|null>(null);
 const [days,setDays]=useState(3),[message,setMessage]=useState(''),[warnings,setWarnings]=useState<string[]>([]);
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>pending.current?.abort(),[]);
 const reset=()=>{pending.current?.abort();pending.current=null;setReady(false);setAgentState('idle');setItinerary(null);setMessage('');setWarnings([])};
 const askAgent=async()=>{
   pending.current?.abort();
   const controller=new AbortController();pending.current=controller;
   setAgentState('thinking');setItinerary(null);setMessage('');setWarnings([]);
   const timeout=setTimeout(()=>controller.abort(new Error('timeout')),600000);
   try{
     const response=await fetch('/api/itinerary',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({destination:place,startDate:date,days,budget,travelers,interests})});
     if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('The planner backend is not connected on this hosted preview. Open the local Roam app to use Ollama.');
     const payload=await response.json() as {itinerary?:Itinerary;error?:string;warnings?:string[]};
     if(!response.ok||!payload.itinerary)throw new Error(response.status===503?'Place search isn’t connected yet. Please try again once travel data is enabled.':payload.error||'The agent could not create a verified itinerary.');
     if(pending.current!==controller)return;
     setItinerary(payload.itinerary);setWarnings(payload.warnings||[]);setAgentState('ready');
   }catch(error){
     if(pending.current!==controller)return;
     setMessage(controller.signal.aborted?'Planning took too long. Try fewer days or restart Ollama.':error instanceof Error?error.message:'Unable to reach the travel agent.');
     setAgentState('error');
   }finally{clearTimeout(timeout);if(pending.current===controller)pending.current=null;}
 };

 return <Dialog open={open} onOpenChange={v=>{onOpenChange(v);if(!v)reset()}}><DialogContent className="brief-dialog"><DialogHeader><span className="eyebrow">YOUR NEXT CHAPTER</span><DialogTitle>{ready?'A little dream. A good beginning.':'Somewhere on your mind?'}</DialogTitle><DialogDescription>{ready?'Your travel brief is ready for the next step.':'Start with a place. We will take the details one little step at a time.'}</DialogDescription></DialogHeader>{ready?<div className="brief-ready"><div className="brief-destination"><MapPin size={21}/><h3>{place}</h3></div><dl><div><dt>Leaving</dt><dd>{new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</dd></div><div><dt>Trip length</dt><dd>{days} {days===1?'day':'days'}</dd></div><div><dt>Travelers</dt><dd>{travelers}</dd></div><div><dt>Trip budget</dt><dd>${budget.toLocaleString()} USD</dd></div>{interests&&<div><dt>Your kind of trip</dt><dd>{interests}</dd></div>}</dl><div className={`agent-preview ${agentState}`}><div className="agent-preview-heading"><Sparkles size={17}/><strong>{agentState==='thinking'?'Roam is shaping the route…':agentState==='ready'?'Your local agent found a route.':agentState==='error'?'We couldn’t complete this plan yet.':'Let’s turn your brief into a journey.'}</strong></div>{itinerary?<p>{itinerary.stops.length} story stops across {itinerary.days} {itinerary.days===1?'day':'days'} · estimated activity cost ${itinerary.totalEstimatedCost.toLocaleString()} USD for the group.</p>:<p role={agentState==='error'?'alert':undefined}>{message||(agentState==='thinking'?'Finding activities and checking weather and driving routes. Local planning can take a few minutes.':'Your local agent uses real places to build a personal itinerary. Weather is available close to departure.')}</p>}<button className="agent-cta" onClick={askAgent} disabled={agentState==='thinking'}>{agentState==='thinking'?'Thinking locally…':agentState==='error'?'Try again':'Ask the Ollama agent'}<ArrowUpRight size={16}/></button></div>{itinerary&&<section className="generated-itinerary" aria-label="Your generated itinerary">
 {Array.from({length:itinerary.days},(_,index)=>index+1).map(day=><article key={day}><h3>Day {day}</h3>{itinerary.weather.filter(w=>w.day===day).map(w=><p className="day-forecast" key={w.date}>{w.condition} · {w.tempLowC}–{w.tempHighC}°C · {w.precipitationChance}% rain</p>)}<ol>{itinerary.stops.filter(stop=>stop.day===day).map(stop=><li key={stop.id}><div><strong>{stop.name}</strong><span>{stop.category} · ≈ ${stop.estimatedCost} / person</span></div><p>{stop.reason}</p>{itinerary.legs?.filter(leg=>leg.toId===stop.id).map(leg=><p className="day-forecast" key={leg.fromId}>From the previous stop: {leg.durationMinutes} min driving · {leg.distanceKm} km</p>)}<a target="_blank" rel="noopener noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(stop.name)+'&query_place_id='+encodeURIComponent(stop.placeId)}>View place ↗</a></li>)}</ol></article>)}
 <p className="data-credit">Places: Google Maps · Forecast: Open-Meteo · Driving estimates: OSRM / OpenStreetMap</p>
 {warnings.length>0&&<details><summary>Data availability notes ({warnings.length})</summary>{warnings.map((warning,index)=><p key={index}>{warning}</p>)}</details>}
 </section>}
 <p className="brief-preview-note">Activity costs are AI estimates, excluding flights and accommodation. Confirm prices and opening hours before booking. The story map is an illustrative sample.</p><button className="primary-cta" onClick={()=>{onOpenChange(false);reset();onDemo()}}>Explore a sample journey<ArrowUpRight size={18}/></button><button className="brief-edit" onClick={reset}>Edit your travel brief</button></div>:<form onSubmit={e=>{e.preventDefault();if(place.trim())setReady(true)}}><label className="field-label" htmlFor="dream-destination"><MapPin size={15}/>Where would you love to go?</label><input id="dream-destination" autoComplete="off" placeholder="A city, a country, somewhere you dream of..." maxLength={100} required value={place} onChange={e=>setPlace(e.target.value)}/><div className="form-row"><div><label className="field-label" htmlFor="dream-date"><CalendarDays size={15}/>When do you leave?</label><input id="dream-date" type="date" required min={new Date().toISOString().slice(0,10)} max="2030-12-31" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label className="field-label" htmlFor="dream-travelers"><Users size={15}/>How many people?</label><input id="dream-travelers" type="number" required min="1" max="30" value={travelers||''} onChange={e=>setTravelers(Number(e.target.value))}/></div></div><label className="field-label" htmlFor="dream-days"><CalendarDays size={15}/>How many days?</label><input id="dream-days" type="number" required min="1" max="14" value={days||''} onChange={e=>setDays(Number(e.target.value))}/><label className="field-label" htmlFor="dream-budget"><Wallet size={15}/>Your total trip budget · USD</label><div className="money-input"><span>$</span><input id="dream-budget" type="number" required min="50" max="1000000" value={budget||''} onChange={e=>setBudget(Number(e.target.value))}/></div><label className="field-label" htmlFor="dream-style"><Compass size={15}/>What makes a trip feel like you?</label><textarea id="dream-style" rows={3} maxLength={600} placeholder="Slow mornings, local food, hiking, travelling with friends..." value={interests} onChange={e=>setInterests(e.target.value)}/><button className="primary-cta" type="submit">Create my travel brief<ArrowUpRight size={18}/></button><p className="form-disclaimer">No account needed. Your brief can be sent to the local Ollama agent when it is running.</p></form>}</DialogContent></Dialog>
}
